### ISSUE TITLE
Xposed error

### ISSUE THREAD

**Issue by Alexey71** [iptux/XCallRecording-xposed#1]
Hello
[xposed_error_20161012_012311.log.txt](https://github.com/iptux/XCallRecording-xposed/files/523095/xposed_error_20161012_012311.log.txt)

**Comment by iptux** [comment]
it's not an error of this module.
`mCall` is `null` here: https://github.com/CyanogenMod/android_packages_apps_InCallUI/blob/cm-13.0/src/com/android/incallui/CallButtonPresenter.java#L396

**Comment by iptux** [comment]
try version 1.0.1! if the problem still exist, reopen this issue
