### ISSUE TITLE
Audio Input Error | Blank recording

### ISSUE THREAD

**Issue by hockeymikey** [iptux/XCallRecording-xposed#13]
Any recording that is taken is blank (the audio files have size but it's just blank static that is recorded).  Other configurations do not work/give more errors than the one below.

Device: Droid 4, CM11 (20160815-UNOFFICIAL-maserati)

Force Audio Source disabled (Get a "Failed to start recording" error toast and the following errors in log if enabled)
`Error: Could not get audio input for record source of 4`
`Error: audio source is not initialized`
`Error: start failed: -2147483648`

Use AAC Format enabled (Encoding codec error is thrown otherwise)

Using that configuration I get this error:
`Error: AudioStreamInMot::Set:Hi-fi call recording not supported`
`Error: InputDevice unable to open or no longer available; sleeping through read()`

**Comment by iptux** [comment]
It seems that your device don't have well support for call recording, you may ask your device's maintainer for help.

**Comment by hockeymikey** [comment]
Maintainer of the ROM or actual device?  Is there any possibility of a work around if no support from a maintainer can be given?

**Comment by hockeymikey** [comment]
This is old but why is this closed @iptux ? You never answered my question either.
