### ISSUE TITLE
REGRESSION: Call recording fails to start on axon7 1.0.10

### ISSUE THREAD

**Issue by BoBeR182** [iptux/XCallRecording-xposed#15]
After upgrading to 1.0.10 on LOS 14.1 on the axon7 device audio recording fails to start on it's own.

**Comment by iptux** [comment]
Do you mean old version works?
Would you provide more info, like log of Xposed installer?

**Comment by BoBeR182** [comment]
Version 1.0.9 works perfectly. Do you want logs from 1.0.10 or 1.0.9 ?

**Comment by PhiloAnthropos** [comment]
Hi, - Recordings are not starting automatically - I am having to manually start them- is there a fix for this please?

![screenshot_20171221-175726](https://user-images.githubusercontent.com/32436165/34267705-215be950-e67e-11e7-8153-31cf91942b0e.png)
![screenshot_20171221-181215](https://user-images.githubusercontent.com/32436165/34267713-25b1ce98-e67e-11e7-8b22-beebdb67b092.jpg)

**Comment by iptux** [comment]
I have upload a new version `1.0.10-verbose` which contains lots of debug logs, please install this version, make a call and send the log to me. the log is available in the Xposed Installer app.

**Comment by PhiloAnthropos** [comment]
Sorry iv taken so long - im abroad and its harder to get stuff done. Log - it dosnt seem to want to give me one???
![whatsapp image 2017-12-28 at 20 50000 11](https://user-images.githubusercontent.com/32436165/34423236-8f9d32cc-ec12-11e7-844b-fdc083512b50.jpg)
I installed the new version but the behavior was the same - any ideas?

**Comment by iptux** [comment]
@PhiloAnthropos 
It's a problem about Xposed Installer. 
Have you tried uninstall Xposed Installer then install Xposed Installer then reboot? If not help, I have no solution too.

@BoBeR182 could you send logs from `1.0.10-verbose` to me?
