### ISSUE TITLE
Call recording fails to start - Lineage OS 14.1 by Teamsuperluminal

### ISSUE THREAD

**Issue by watyqem** [iptux/XCallRecording-xposed#16]
A message appears "Failed to start call recording" at Lineage OS 14.1 by Teamsuperluminal. Storage permissions granted. What should I do ?

**Comment by iptux** [comment]
This message comes from Dialer app. if call recording cannot start manually, it cannot start automatically.

https://github.com/LineageOS/android_packages_apps_Dialer/blob/cm-14.1/InCallUI/src/com/android/incallui/CallRecorder.java#L123
