### ISSUE TITLE
Second incoming call stops recording of first/current call

### ISSUE THREAD

**Issue by matahata** [iptux/XCallRecording-xposed#18]
When there is recording running with the current call, a second incoming call is causing to abort the recording of the first call. (This happens as soon as the second caller stops his call request). Do you have any idea how to solve this issue?

I assume that there is something like a "Call End" Event, that will be catched and stop doing the recording.. In this case it catches the wrong event..

**Comment by iptux** [comment]
```
Call 1:  a|------------------|d
Call 2:         b|------|c
```

Do you mean recording for `Call 1` stopped at point `c`? This might because the recorder do not support multiple recording at the same time.

I have no idea how to solve this issue. And what this module do is click the recording button when the phone enters `IN_CALL` state.

**Comment by matahata** [comment]
Right, correct, as you described.

Okay, thanks for your response.
