### ISSUE TITLE
dialer v11

### ISSUE THREAD

**Issue by zakijesk** [iptux/XCallRecording-xposed#20]
is it possible to update this great module to work with the dialer app used on oreo roms aosp and lineage os 15.1 and the roms based on them ?
I included its apk
[Dialer.zip](https://github.com/iptux/XCallRecording-xposed/files/2140982/Dialer.zip)

**Comment by iptux** [comment]
Unfortunately, Lineage OS 15 and 15.1 don't have call recorder inside the Dialer app. This module will not work on such ROM.
