### ISSUE TITLE
Support Module on Other Rom Bases (AOSP GZAOSP, etc) 

### ISSUE THREAD

**Issue by ricksee** [iptux/XCallRecording-xposed#25]
Would it be possible to add support for other roms that dont have lineageOS as its base such as AOSP, AEX, Pixel Experience?

**Comment by iptux** [comment]
Possible, but require lot's of work.

**Comment by ricksee** [comment]
Thanks alot.

**Comment by zakijesk** [comment]
it wasn't working because the dialer didn't have the call recording feature, now that they put it back in version 5.8 of AEX which I have on my phone it's working fine

**Comment by ricksee** [comment]
@zakijesk Thanks for the heads up. Can confirm its working. Do you know any roms that also have this feature?

**Comment by zakijesk** [comment]
@ricksee sorry this is the only I have tested recently, check the changelog or the features list of the rom they might mention it there
mostly roms based on AOSP that was updated during the last month should have this feature

**Comment by ricksee** [comment]
@zakijesk Okay so I tested all the major ROMS on my OnePlus 5T and it only AEX supports it. However, I can only hear myself as the sound from the other end is muffled.
