### ISSUE TITLE
Installed But There is no App :S

### ISSUE THREAD

**Issue by hasanalizxc** [iptux/XCallRecording-xposed#27]
Hi All,

I am using LOS 14.1 and installed this via Xposed but there is no application. It just installed.

Can you help me?

**Comment by iptux** [comment]
Try `Xposed Installer -> Modules`

**Comment by hasanalizxc** [comment]
> 
> 
> Try `Xposed Installer -> Modules`

I already installed with that way and enabled, rebooted. It is installed but there is no application. Think like a service.

**Comment by vwugd97** [comment]
The module does not create a Icon to click in a launcher.

As iptux already told you, you have to open the Xposed Module overview and just click on the "XCallRecordingSettings" entry.
