### ISSUE TITLE
Records are not in their directories

### ISSUE THREAD

**Issue by ia5634** [iptux/XCallRecording-xposed#36]
Firstly, thanks so much for this long-living app.

The app is configured to separate folders.
- The app creates a folder named "John Doe" but its records are not in that folder. All records are in "Music\Call Recordings".

Tried many things such as different xposed verisons (Lsposed - Edxposed) but nothing changed. Do you need anything for inspect this issue? Or, how may I help you?

I'm using BlissRom 14.8 (Android 11) on Samsung Note 9 Exynos.

Regards...

**Comment by iptux** [comment]
* it's known on Android 11.
* won't fix so there is a warning on the UI.
* more emphasis the warning on next release.

**Comment by ia5634** [comment]
I saw the a warning about MediaProvider but I thought its related saving/not saving or something like that issue. Didn't know its about the separation. 

I'll try to write a script for moving files after call ends. Just like a workaround. 

Thanks.

**Comment by ia5634** [comment]
Just made a script with Tasker.

It make two dirs (in - out) in folder.
Gets call information if it is incoming or outgoing. 
Moves the record into correct folder.

Did this procedure for entire Call Recordings directory too. Perfect. 

I can share the scripts if it is allowed.

**Comment by ia5634** [comment]
Yes, I was able to play the files without any problems.

I've updated some system components and dialer app became not play. It does not even trying. Keep crashing. Says has no access to "media/bla bla" folder. So I decided back to stock rom :/

I'll wait for a while for somebody finds a solution for this accessing files issue. Because I'm tired of this.
