### ISSUE TITLE
Support LSPosed

### ISSUE THREAD

**Issue by Lvl4Sword** [iptux/XCallRecording-xposed#38]
EdXposed only supports up to Android 11 ( https://github.com/ElderDrivers/EdXposed/releases ) and hasn't had a release in over a year.
Riru also is suggesting migration to Zygisk ( https://github.com/RikkaApps/Riru , in the readme ) and has set their repo to read-only.
With these in mind, it'd be incredibly useful to support being installed through LSPosed ( https://github.com/LSPosed/LSPosed ).
If this project is already supported through LSPosed, a how-to or some info about this would be useful.

Thank you.

**Comment by iptux** [comment]
fixed in 6efeba1f7ca462831cdb703a0364c3c8cf75abb5

**Comment by Lvl4Sword** [comment]
There isn't an option to choose the dialer.
I can choose `System Framework`, which isn't the same and doesn't seem to work.
