### ISSUE TITLE
Add apk to Github Releases

### ISSUE THREAD

**Issue by NikitaBeloglazov** [iptux/XCallRecording-xposed#39]
dl-xda.xposed.info don't works, I can't download the module for days
So please add APK file to Github Releases tab

![image](https://user-images.githubusercontent.com/77229847/189945859-13ce0737-a359-4abb-b8b8-b233dba36b00.png)

**Comment by vazahiri** [comment]
> dl-xda.xposed.info don't works, I can't download the module for days So please add APK file to Github Releases tab
> 
> ![image](https://user-images.githubusercontent.com/77229847/189945859-13ce0737-a359-4abb-b8b8-b233dba36b00.png)

Yes, please add apk.

**Comment by jfromeo** [comment]
Same here. Unable yo download apk for months.
