### ISSUE TITLE
Would be great if you can (somehow) support Android dialer (com.google.android.dialer)

### ISSUE THREAD

**Issue by 1and1get2** [iptux/XCallRecording-xposed#5]

**Comment by iptux** [comment]
I have tried Google's [Phone][] app, and found that it don't have call recording feature(did I miss something?). Without this feature, I cannot start recording with Google's Phone app.

Search `call recording` on Google Play instead.

[Phone]: https://play.google.com/store/apps/details?id=com.google.android.dialer
