### ISSUE TITLE
Vibration setting

### ISSUE THREAD

**Issue by SerVB** [iptux/XCallRecording-xposed#6]
Is there an ability to disable vibration when recording is starting?

**Comment by iptux** [comment]
Bad news, I'm trying to find related code controlling the vibration when recording is starting, but nothing found, neither in `Dialer`/`InCallUi` project, nor in disassemble result of `Dialer.apk` :confused:

**Comment by SerVB** [comment]
OK, I'll try to get used to this feature ;) All in all, the module is pretty cool! Thank you.
