### ISSUE TITLE
Difference between AAC setting in the app and in the dialer

### ISSUE THREAD

**Issue by srustamo** [iptux/XCallRecording-xposed#8]
There are two places where AAC can be set. I set this from within the dialer and it works. How diff is the setting from within this app?

Incidentally, the AMR format does create a recording, but it is silent.

**Comment by iptux** [comment]
Q: Why there is an AAC setting?
A: All related settings should be available in this module.

Q: How the AAC setting take effect?
A: the module's AAC setting has higher priority. When the AAC setting is enabled, recording use AAC. When the AAC setting is disabled, recording will use the settings from Dialer.
